[build]
command = "npm install" 
publish = "." 
functions = "netlify/functions"

[functions]
  # Aumenta o tempo de execução para 60 segundos
  timeout = 60

[functions."sincronizar_bling"]
  # Mantém o agendamento de 5 em 5 minutos
  schedule = "*/5 * * * *"
