[build]
  # O comando de build que o Netlify deve executar
  # Isso garante que o 'npm install' seja rodado antes de tentar rodar as funções
  command = "npm install" 
  
  functions = "netlify/functions"
  publish = "docs" # Mantenha a sua pasta de publicação correta

[functions."sincronizar_bling"]
  schedule = "*/5 * * * *"
